@echo off
del /q ".\setup\builds\*.exe" 2>nul:
del /q ".\setup\builds\*.iss" 2>nul:
del /q ".\setup\builds\*.txt" 2>nul:
rd /s /q ".\vc10\ipch\" 2>nul:
for /r %%i in (*.aps) do del /q "%%i" && echo Cleaning %%i...
for /r %%i in (*.ncb) do del /q "%%i" && echo Cleaning %%i...
for /r %%i in (*.sdf) do del /q "%%i" && echo Cleaning %%i...
for /d /r %%i in (*.*) do if exist "%%i\Win32\" rd /s /q "%%i\Win32\" && echo Cleaning %%i\Win32\...
for /d /r %%i in (*.*) do if exist "%%i\x64\" rd /s /q "%%i\x64\" && echo Cleaning %%i\x64\...
pause