#ifndef __RES_HACK_DEF__
#define __RES_HACK_DEF__

#ifdef 	AFX_IDP_PARSE_INT
#undef 	AFX_IDP_PARSE_INT
#define AFX_IDP_PARSE_INT			40000
#endif
#ifdef	AFX_IDP_PARSE_REAL
#undef	AFX_IDP_PARSE_REAL
#define AFX_IDP_PARSE_REAL			40001
#endif
#ifdef	AFX_IDP_PARSE_INT_RANGE
#undef	AFX_IDP_PARSE_INT_RANGE
#define AFX_IDP_PARSE_INT_RANGE		40002
#endif
#ifdef	AFX_IDP_PARSE_REAL_RANGE
#undef	AFX_IDP_PARSE_REAL_RANGE
#define AFX_IDP_PARSE_REAL_RANGE	40003
#endif
#ifdef	AFX_IDP_PARSE_STRING_SIZE
#undef	AFX_IDP_PARSE_STRING_SIZE
#define AFX_IDP_PARSE_STRING_SIZE	40004
#endif
#ifdef	AFX_IDP_PARSE_RADIO_BUTTON
#undef	AFX_IDP_PARSE_RADIO_BUTTON
#define AFX_IDP_PARSE_RADIO_BUTTON	40005
#endif
#ifdef	AFX_IDP_PARSE_BYTE
#undef	AFX_IDP_PARSE_BYTE
#define AFX_IDP_PARSE_BYTE			40006
#endif
#ifdef	AFX_IDP_PARSE_UINT
#undef	AFX_IDP_PARSE_UINT
#define AFX_IDP_PARSE_UINT			40007
#endif
#ifdef	AFX_IDP_PARSE_DATETIME
#undef	AFX_IDP_PARSE_DATETIME
#define AFX_IDP_PARSE_DATETIME		40008
#endif
#ifdef	AFX_IDP_PARSE_CURRENCY
#undef	AFX_IDP_PARSE_CURRENCY
#define AFX_IDP_PARSE_CURRENCY		40009
#endif
#ifdef	AFX_IDP_PARSE_GUID
#undef	AFX_IDP_PARSE_GUID
#define AFX_IDP_PARSE_GUID			40010
#endif
#ifdef	AFX_IDP_PARSE_TIME
#undef	AFX_IDP_PARSE_TIME
#define AFX_IDP_PARSE_TIME			40011
#endif
#ifdef	AFX_IDP_PARSE_DATE
#undef	AFX_IDP_PARSE_DATE
#define AFX_IDP_PARSE_DATE			40012
#endif

#endif // __RES_HACK_DEF__
