//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Shareaza.rc
//
#define IDR_MANIFEST                    1
#define IDC_SETUP                       3
#define IDD_SETTINGS_CONNECTION         107
#define IDR_POPUPS                      126
#define IDB_MENUBAR                     127
#define IDR_MAINFRAME                   128
#define IDR_SYSTEMFRAME                 129
#define IDR_NEIGHBOURSFRAME             130
#define IDR_PACKETFRAME                 131
#define IDR_HOSTCACHEFRAME              132
#define IDR_SEARCHMONITORFRAME          133
#define IDR_SEARCHFRAME                 134
#define IDR_HITMONITORFRAME             135
#define IDR_DOWNLOADSFRAME              136
#define IDB_SORT_ASC                    137
#define IDR_LIBRARYFRAME                137
#define IDB_SORT_DESC                   138
#define IDD_CONNECT_TO                  138
#define IDR_UPLOADSFRAME                138
#define IDD_NEW_SEARCH                  139
#define IDB_SHELL_BASE                  139
#define IDR_TRAFFICFRAME                139
#define IDD_FILTER_SEARCH               140
#define IDB_FOLDERS                     140
#define IDR_CHATFRAME                   140
#define IDR_SECURITYFRAME               141
#define IDD_SCHEMA_COLUMNS              141
#define IDD_FILE_PROPERTIES             142
#define IDR_DISCOVERYFRAME              142
#define IDR_BROWSEHOSTFRAME             143
#define IDD_SETTINGS_GNUTELLA           143
#define IDR_HOMEFRAME                   144
#define IDD_SETTINGS_ADVANCED           144
#define IDD_SETTINGS_DOWNLOADS          145
#define IDR_MEDIAFRAME                  145
#define IDD_SETTINGS_UPLOADS            146
#define IDR_SEARCHPADFRAME              146
#define IDD_SETTINGS_GENERAL            147
#define IDC_HAND                        147
#define IDR_HELPFRAME                   147
#define IDD_ABOUT                       148
#define IDD_FILTER_SAVE_AS              149
#define IDD_GRAPH_LIST                  150
#define IDD_GRAPH_ITEM                  151
#define IDB_COLOURDOT                   151
#define IDD_WIZARD_WELCOME              152
#define IDD_WIZARD_CONNECTION           153
#define IDB_WIZARD                      154
#define IDD_WIZARD_SHARING              154
#define IDD_WIZARD_FINISHED             155
#define IDB_WIZARD_DOT                  158
#define IDR_CHILDFRAME                  159
#define IDD_FOLDER_SCAN                 160
#define IDB_SECURITY                    160
#define IDI_BROWSE                      160
#define IDR_HIDDEN                      161
#define IDD_DOWNLOAD                    162
#define IDD_BITZI_DOWNLOAD              163
#define IDD_SECURE_RULE                 165
#define IDD_FILE_COPY                   167
#define IDD_URL_ACTION                  168
#define IDD_WIZARD_INTERFACE            169
#define IDD_URL_COPY                    172
#define IDD_SPLASH                      173
#define IDD_DISCOVERY_SERVICE           174
#define IDI_WEB_URL                     175
#define IDD_SETTINGS_BANDWIDTH          175
#define IDD_URL_EXPORT                  176
#define IDD_UPGRADE                     177
#define IDD_SETTINGS_COMMUNITY          178
#define IDD_DOWNLOAD_MONITOR            180
#define IDI_EXECUTABLE                  181
#define IDD_SETTINGS_SKINS              181
#define IDI_SKIN                        182
#define IDD_FILE_PREVIEW                182
#define IDI_POINTER_ARROW               183
#define IDD_LANGUAGE                    183
#define IDD_SETTINGS_RICH               184
#define IDI_WORLD                       185
#define IDD_SETTINGS_PLUGINS            185
#define IDI_FLAG_ENGLISH                186
#define IDD_FOLDER_PROPERTIES           186
#define IDD_SETTINGS_MEDIA              187
#define IDI_CHECKMARK                   188
#define IDD_SETTINGS_INTERFACE          188
#define IDD_SETTINGS_LIBRARY            189
#define IDD_FILE_METADATA               190
#define IDI_FILE                        191
#define IDD_FILE_GENERAL                191
#define IDD_FILE_SOURCES                192
#define IDB_FORTYEIGHT                  193
#define IDC_COPY                        194
#define IDC_MOVE                        195
#define IDR_LARGE_LOGO                  196
#define IDD_SETTINGS_WEB                198
#define IDD_PROFILE_IDENTITY            199
#define IDI_HOST_OUTGOING               200
#define IDI_HOST_INCOMING               201
#define IDD_PROFILE_FAVOURITES          201
#define IDI_PROPERTIES                  202
#define IDD_PROFILE_PROFILE             202
#define IDI_DOWNLOAD_MONITOR            203
#define IDD_PROFILE_CONTACT             204
#define IDD_PROFILE_BIO                 205
#define IDD_PROFILE_FILES               206
#define IDI_CONTACT_YAHOO               206
#define IDD_PROFILE_CERTIFICATE         207
#define IDI_CONTACT_AOL                 207
#define IDD_SHARE_MANAGER               208
#define IDI_CONTACT_ICQ                 208
#define IDD_PROFILE_AVATAR              209
#define IDD_MEDIA_VIS                   210
#define IDD_WIZARD_PROFILE              211
#define IDI_COMPUTER_GRAY               212
#define IDD_FILE_COMMENTS               212
#define IDI_DISCOVERY_GRAY              213
#define IDD_WARNINGS                    213
#define IDI_SEARCH_FOLDER               214
#define IDD_PROMOTE                     214
#define IDI_DISCOVERY_BLUE              215
#define IDB_SMALL_STAR                  216
#define IDD_EXISTING_FILE               217
#define IDD_CLOSE_MODE                  218
#define IDD_SETTINGS_DONKEY             219
#define IDD_SETTINGS_NETWORKS           220
#define IDB_BANNER_MARK                 221
#define IDD_SETTINGS_PROTOCOLS          221
#define IDB_MEDIA_STATES                222
#define IDD_QUEUE_PROPERTIES            222
#define IDD_SETTINGS_BITTORRENT         223
#define IDB_TASKPANEL_FOOTER            224
#define IDB_TASKBOX_CAPTION             225
#define IDB_PROTOCOLS                   227
#define IDD_DONKEY_SERVERS              230
#define IDD_WIZARD_NETWORKS             231
#define IDD_FILE_SHARING                232
#define IDD_DONKEY_IMPORT               235
#define IDI_CLIPBOARD                   236
#define IDD_DOWNLOAD_GROUP              236
#define IDI_PAINTBRUSHES                237
#define IDD_TORRENT_TRACKER             238
#define IDR_TORRENT_ICON                239
#define IDD_HELP                        240
#define IDB_NAVBAR_IMAGE                241
#define IDD_DELETE_FILE                 242
#define IDI_COLLECTION_MASK             243
#define IDI_COLLECTION                  244
#define IDD_COLLECTION_EXPORT           245
#define IDB_NAVBAR_ALPHA                246
#define IDD_TORRENT_SEED                247
#define IDB_REMOTE_SKIN                 248
#define IDD_DOWNLOAD_EDIT               248
#define IDD_SETTINGS_REMOTE             249
#define IDD_SETTINGS_SCHEDULER          250
#define IDD_DOWNLOAD_REVIEWS            251
#define IDI_FIREWALLED                  252
#define IDI_MERCORA                     254
#define IDR_MERCORA_BUTTON              255
#define IDR_HOME_HEADER_1               257
#define IDR_HOME_HEADER_2               258
#define IDR_SPLASH                      259
#define IDI_SMALL                       260
#define IDI_ICON                        261
#define IDB_BITMAP1                     262
#define IDB_PANEL_MARK                  262
#define IDI_ICON1                       263
#define IDR_BITTORRENT_ICON             263
#define IDI_MAIL                        265
#define IDB_BITMAP3                     265
#define IDD_CODEPAGES                   266
#define IDB_SCHEDULER_HEADER            270
#define IDB_SCHEDULER_TIMESLICES        271
#define IDC_CONNECT_HOST                1000
#define IDC_CONNECT_PORT                1001
#define IDC_SCHEMAS                     1002
#define IDC_SEARCH                      1004
#define IDC_FILTER                      1005
#define IDC_COLUMNS                     1006
#define IDI_COMPUTER                    1006
#define IDC_CONNECT_ULTRAPEER           1007
#define IDI_CONTACT_MSN                 1007
#define IDC_FILE_SHA1                   1009
#define IDC_FILE_TYPE                   1010
#define IDC_FILE_SIZE                   1011
#define IDC_FILE_ICON                   1012
#define IDC_FILE_NAME                   1013
#define IDC_FILE_PATH                   1014
#define IDC_FILE_URN                    1014
#define IDC_INBOUND_HOST                1015
#define IDC_FILE_INDEX                  1015
#define IDC_INBOUND_PORT                1016
#define IDC_FILE_TIGER                  1016
#define IDC_OUTBOUND_HOST               1017
#define IDC_FILE_MODIFIED               1017
#define IDC_FILE_MD5                    1018
#define IDC_FILE_ED2K                   1019
#define IDC_INBOUND_SPEED               1020
#define IDC_CAN_ACCEPT                  1021
#define IDC_TIMEOUT_CONNECTION          1022
#define IDC_TIMEOUT_HANDSHAKE           1023
#define IDC_ULTRAPEER_ENABLE            1023
#define IDC_ULTRAPEER_FORCE             1024
#define IDC_OUTBOUND_SPEED              1024
#define IDC_ULTRALEAF_ENABLE            1025
#define IDC_ULTRALEAF_FORCE             1026
#define IDC_MAX_PEERS                   1027
#define IDC_G2_PEERS                    1027
#define IDC_MAX_PEERS_SPIN              1028
#define IDC_G2_PEERS_SPIN               1028
#define IDC_MAX_LEAFS                   1029
#define IDC_G2_LEAFS                    1029
#define IDC_MAX_LEAFS_SPIN              1030
#define IDC_G2_LEAFS_SPIN               1030
#define IDC_AGENT                       1031
#define IDC_MAX_HUBS                    1032
#define IDC_G2_HUBS                     1032
#define IDC_MAX_HUBS_SPIN               1033
#define IDC_G2_HUBS_SPIN                1033
#define IDC_G1_HUBS                     1034
#define IDC_G1_HUBS_SPIN                1035
#define IDC_G1_LEAFS                    1036
#define IDC_G1_LEAFS_SPIN               1037
#define IDC_G1_PEERS                    1038
#define IDC_G1_PEERS_SPIN               1039
#define IDC_PROPERTIES                  1040
#define IDC_REQUIRE_CONNECT             1043
#define IDC_INCOMPLETE_FOLDER           1044
#define IDC_INCOMPLETE_BROWSE           1045
#define IDC_DOWNLOADS_FOLDER            1046
#define IDC_DOWNLOADS_BROWSE            1047
#define IDC_MAX_FILES                   1048
#define IDC_MAX_FILES_SPIN              1049
#define IDC_MAX_TRANSFERS               1050
#define IDC_MAX_TRANSFERS_SPIN          1051
#define IDC_MAX_TPF                     1052
#define IDC_MAX_TPF_SPIN                1053
#define IDC_DOWNLOADS_BANDWIDTH_LIMIT   1055
#define IDC_DOWNLOADS_QUEUE_LIMIT       1056
#define IDC_MAX_HOST                    1059
#define IDC_MAX_HOST_SPIN               1060
#define IDC_SOURCE_MESH                 1061
#define IDC_HIGH_HASH                   1061
#define IDC_WATCH_FOLDERS               1062
#define IDC_STORE_VIEWS                 1063
#define IDC_TIMEOUT_CONNECTION_SPIN     1064
#define IDC_BROWSE_FILES                1064
#define IDC_TIMEOUT_HANDSHAKE_SPIN      1065
#define IDC_VALUE                       1065
#define IDC_VALUE_SPIN                  1066
#define IDC_SHARE_PARTIALS              1066
#define IDC_GRAPH_ITEMS                 1067
#define IDC_SHARE_PREVIEW               1067
#define IDC_GRAPH_ADD                   1068
#define IDC_HUB_UNSHARE                 1068
#define IDC_GRAPH_EDIT                  1069
#define IDC_SHARE_PREVIEW_DYNAMIC       1069
#define IDC_VIRTUAL_FILES               1069
#define IDC_GRAPH_LEGEND                1071
#define IDC_GRAPH_AXIS                  1072
#define IDC_GRAPH_SOURCE                1072
#define IDC_GRAPH_GRID                  1073
#define IDC_GRAPH_PARAM                 1073
#define IDC_GRAPH_UNITS                 1074
#define IDC_GRAPH_COLOUR                1075
#define IDC_GRAPH_COLOUR_BOX            1076
#define IDC_GRAPH_REMOVE                1077
#define IDC_GRAPH_SPEED                 1078
#define IDC_GRAPH_SPEED_SPIN            1079
#define IDC_INBOUND_BIND                1082
#define IDC_INBOUND_RANDOM              1083
#define IDC_CHAT_ENABLE                 1084
#define IDC_RATES_IN_BYTES              1085
#define IDC_CHAT_ALLNETWORKS            1085
#define IDC_CHAT_FILTER                 1086
#define IDC_EXPAND_MATCHES              1087
#define IDC_CONNECTION_TYPE             1087
#define IDC_CHAT_CENSOR                 1087
#define IDC_CONNECTION_SPEED            1088
#define IDC_SHARE_FOLDERS               1088
#define IDC_SCHEMA_TYPES                1088
#define IDC_HIGHLIGHT_NEW               1088
#define IDC_SHARE_ADD                   1089
#define IDC_CLOSE_MODE                  1089
#define IDC_CONNECTION_LAN_SELECT       1089
#define IDC_SHARE_REMOVE                1090
#define IDC_CONNECTION_GROUP            1090
#define IDC_WEB                         1091
#define IDC_AUTO_CONNECT                1091
#define IDC_CONNECTION_HOME_SELECT      1091
#define IDC_TITLE                       1092
#define IDC_TRAY_MINIMISE               1092
#define IDC_FILTER_PUSH                 1093
#define IDC_AUTO_START                  1093
#define IDC_FILTER_BUSY                 1094
#define IDC_SWITCH_TO_TRANSFERS         1094
#define IDC_FILTER_UNSTABLE             1095
#define IDC_EXPAND_DOWNLOAD             1095
#define IDC_FILTER_REJECT               1096
#define IDC_PROMPT_URLS                 1096
#define IDC_FILTER_LOCAL                1097
#define IDC_PROMPT_URLS2                1097
#define IDC_FILTER_BOGUS                1098
#define IDC_MIN_SIZE                    1099
#define IDC_MAX_SIZE                    1100
#define IDC_SCAN_FILE                   1100
#define IDC_SCAN_FILES                  1101
#define IDC_SOURCES                     1101
#define IDC_SCAN_VOLUME                 1102
#define IDC_URL                         1102
#define IDC_CAPTION                     1103
#define IDC_PROGRESS                    1104
#define IDC_PROGRESS_FILE               1105
#define IDC_DOWNLOAD_GRAPH              1105
#define IDC_HIDE_SEARCH                 1106
#define IDC_ADULT_FILTER                1107
#define IDC_IP_1                        1108
#define IDC_CLEAR_DOWNLOADS             1108
#define IDC_IP_2                        1109
#define IDC_CLEAR_UPLOADS               1109
#define IDC_IP_3                        1110
#define IDC_IP_4                        1111
#define IDC_MASK_1                      1112
#define IDC_MASK_2                      1113
#define IDC_MASK_3                      1114
#define IDC_MASK_4                      1115
#define IDC_RULE_ACTION                 1116
#define IDC_RULE_EXPIRE                 1117
#define IDC_MESSAGE                     1117
#define IDC_EXPIRE_D                    1118
#define IDC_EXPIRE_H                    1119
#define IDC_PLACEHOLDER                 1119
#define IDC_EXPIRE_M                    1120
#define IDC_FILES                       1120
#define IDC_IGNORE_LOCAL                1121
#define IDC_RULE_TYPE                   1121
#define IDC_URL_DOWNLOAD                1122
#define IDC_URL_SEARCH                  1123
#define IDC_URL_NAME_VALUE              1124
#define IDC_URL_NAME_TITLE              1125
#define IDC_URL_URN_TITLE               1126
#define IDC_URL_URN_VALUE               1127
#define IDC_MESSAGE_1                   1128
#define IDC_INTERFACE_0                 1129
#define IDC_INTERFACE_1                 1130
#define IDC_MESSAGE_2                   1131
#define IDC_DESCRIPTION_0               1131
#define IDC_DESCRIPTION_1               1132
#define IDC_MESSAGE_3                   1132
#define IDC_WIZARD_CONNECT              1133
#define IDC_MESSAGE_4                   1133
#define IDC_WIZARD_AUTO                 1134
#define IDC_URL_MAGNET                  1135
#define IDC_WIZARD_STARTUP              1135
#define IDC_URL_HOST                    1137
#define IDC_URL_ED2K                    1138
#define IDC_ADDRESS                     1140
#define IDC_SERVICE_TYPE                1141
#define IDC_HASH_INTEGRITY              1142
#define IDC_UPIN_LIMIT                  1144
#define IDC_UPIN_MAX                    1145
#define IDC_UPIN_TOTAL                  1146
#define IDC_UPIN_SPIN                   1147
#define IDC_UPIN_SPIN2                  1148
#define IDC_PIN_LIMIT                   1150
#define IDC_PIN_MAX                     1151
#define IDC_PIN_TOTAL                   1152
#define IDC_HEAD_RECEIVE                1153
#define IDC_HEAD_TRANSMIT               1154
#define IDC_HEAD_UP_1                   1155
#define IDC_DL_TOTAL                    1158
#define IDC_PIN_SPIN                    1159
#define IDC_HEAD_UP_2                   1161
#define IDC_UPOUT_LIMIT                 1162
#define IDC_UPOUT_SPIN                  1163
#define IDC_URL_FORMAT                  1163
#define IDC_UPOUT_MAX                   1164
#define IDC_URL_TOKEN                   1164
#define IDC_UPOUT_TOTAL                 1165
#define IDC_URL_PRESET                  1165
#define IDC_POUT_LIMIT                  1166
#define IDC_POUT_SPIN                   1167
#define IDC_POUT_MAX                    1168
#define IDC_RULE_COMMENT                1168
#define IDC_POUT_TOTAL                  1169
#define IDC_DONT_CHECK                  1169
#define IDC_FILE_HASH_LABEL             1170
#define IDC_LOC_CITY                    1172
#define IDC_UL_TOTAL                    1173
#define IDC_LOC_COUNTRY                 1173
#define IDC_IN_TOTAL                    1174
#define IDC_PROFILE_NICK                1174
#define IDC_OUT_TOTAL                   1175
#define IDC_PROFILE_FIRST               1175
#define IDC_LOC_LAT                     1176
#define IDC_LIN_LIMIT                   1176
#define IDC_LOC_LONG                    1177
#define IDC_SOURCES_SPIN                1177
#define IDC_LIN_SPIN                    1177
#define IDC_DOWNLOAD_STOP               1178
#define IDC_PROFILE_EMAIL               1178
#define IDC_LIN_MAX                     1178
#define IDC_DOWNLOAD_LAUNCH             1179
#define IDC_PROFILE_LAST                1179
#define IDC_LIN_TOTAL                   1179
#define IDC_DOWNLOAD_LIBRARY            1180
#define IDC_LOUT_LIMIT                  1180
#define IDC_DOWNLOAD_FILE               1181
#define IDC_LOUT_SPIN                   1181
#define IDC_DOWNLOAD_STATUS             1182
#define IDC_LOUT_MAX                    1182
#define IDC_DOWNLOAD_TIME               1183
#define IDC_LOUT_TOTAL                  1183
#define IDC_DOWNLOAD_SOURCES            1184
#define IDC_DOWNLOAD_CLOSE              1185
#define IDC_DOWNLOAD_SPEED              1186
#define IDC_LIN_SPIN2                   1186
#define IDC_DOWNLOAD_ICON               1187
#define IDC_UDP_TOTAL                   1187
#define IDC_DOWNLOAD_CANCEL             1188
#define IDC_PIN_SPIN2                   1188
#define IDC_NEW_WINDOW                  1189
#define IDC_DOWNLOAD_VOLUME             1189
#define IDC_DL_SPIN2                    1189
#define IDC_GROUP_NETWORK               1190
#define IDC_ALWAYS_OPEN                 1190
#define IDC_UPOUT_SPIN2                 1190
#define IDC_GROUP_CONTENT               1191
#define IDC_LOUT_SPIN2                  1191
#define IDC_RULE_CONTENT                1192
#define IDC_POUT_SPIN2                  1192
#define IDC_RULE_MATCH_0                1193
#define IDC_UL_SPIN2                    1193
#define IDC_RULE_MATCH_1                1194
#define IDC_SKINS                       1194
#define IDC_UDP_SPIN2                   1194
#define IDC_INCLUDE_SELF                1195
#define IDC_CONNECT_PROMPT              1196
#define IDC_PREVIEW_STATUS              1198
#define IDC_SKINS_WEB                   1199
#define IDC_SKINS_BROWSE                1200
#define IDC_SKIN_DESC                   1201
#define IDC_SKIN_AUTHOR                 1202
#define IDC_SKIN_NAME                   1203
#define IDC_SKINS_DELETE                1204
#define IDC_DESCRIPTION                 1204
#define IDC_G1_ALWAYS                   1205
#define IDC_PLUGINS_WEB                 1206
#define IDC_G1_TODAY                    1206
#define IDC_GUID                        1207
#define IDC_PLUGINS_SETUP               1207
#define IDC_G2_TODAY                    1207
#define IDC_DEFLATE_HUB2LEAF            1208
#define IDC_GUID_TIME                   1209
#define IDC_DEFLATE_HUB2HUB             1209
#define IDC_GUID_CREATE                 1210
#define IDC_DEFLATE_LEAF2HUB            1210
#define IDC_PROFILE_GENDER              1211
#define IDC_EDIT_PROFILE                1211
#define IDC_VIS_SIZE                    1212
#define IDC_FILE_RATING                 1212
#define IDC_CONNECT_PROTOCOL            1212
#define IDC_MARKED_LIST                 1212
#define IDC_PROFILE_AGE                 1213
#define IDC_SHOW_SYSTEM                 1215
#define IDC_MEDIA_PLAY                  1216
#define IDC_MEDIA_ENQUEUE               1217
#define IDC_MEDIA_ADD                   1218
#define IDC_MEDIA_REMOVE                1219
#define IDC_MEDIA_TYPES                 1220
#define IDC_TIP_DELAY                   1221
#define IDC_TIP_ALPHA                   1222
#define IDC_TIP_DISPLAY                 1223
#define IDC_TIP_DELAY_SPIN              1224
#define IDC_SAFE_TYPES                  1225
#define IDC_SAFE_ADD                    1226
#define IDC_SAFE_REMOVE                 1227
#define IDC_PRIVATE_TYPES               1228
#define IDC_AGENT_LIST                  1228
#define IDC_PRIVATE_ADD                 1229
#define IDC_AGENT_ADD                   1229
#define IDC_PRIVATE_REMOVE              1230
#define IDC_AGENT_REMOVE                1230
#define IDC_MESSAGE_COPY                1231
#define IDC_MESSAGE_MOVE                1232
#define IDC_RECENT_TOTAL                1232
#define IDC_RECENT_TOTAL_SPIN           1233
#define IDC_RECENT_DAYS                 1234
#define IDC_RECENT_DAYS_SPIN            1235
#define IDC_RECENT_CLEAR                1236
#define IDC_FILE_SHARE                  1238
#define IDC_FILE_SOURCE                 1240
#define IDC_FILE_SOURCES                1241
#define IDC_SOURCE_NEW                  1242
#define IDC_SOURCE_REMOVE               1243
#define IDC_BETA_NAME                   1243
#define IDC_BETA_PASSWORD               1244
#define IDC_BETA_STATUS                 1245
#define IDC_PLUGINS                     1246
#define IDC_URI_MAGNET                  1248
#define IDC_URI_GNUTELLA                1249
#define IDC_SHARE_OVERRIDE_0            1249
#define IDC_URI_ED2K                    1250
#define IDC_SHARE_OVERRIDE_1            1250
#define IDC_PROFILE_YAHOO               1250
#define IDC_WEB_HOOK                    1251
#define IDC_PROFILE_ICQ                 1251
#define IDC_WEB_LIST                    1251
#define IDC_PROFILE_AOL                 1252
#define IDC_WEB_URL                     1252
#define IDC_URI_PIOLET                  1252
#define IDC_WEB_NAME                    1253
#define IDC_PROFILE_MSN                 1253
#define IDC_URI_TORRENT                 1253
#define IDC_WEB_ADD                     1254
#define IDC_WEB_REMOVE                  1255
#define IDC_INTEREST_LIST               1256
#define IDC_INTEREST_ALL                1257
#define IDC_INTEREST_ADD                1258
#define IDC_INTEREST_REMOVE             1259
#define IDC_PROFILE_BIO                 1259
#define IDC_FILE_LIST                   1260
#define IDC_PREVIEW                     1262
#define IDC_AVATAR_BROWSE               1263
#define IDC_AVATAR_REMOVE               1264
#define IDC_MEDIA_SERVICE               1264
#define IDC_MEDIA_VIS                   1265
#define IDC_PROFILE_EDIT                1266
#define IDC_EXT_LIST                    1267
#define IDC_EXT_ADD                     1268
#define IDC_EXT_REMOVE                  1269
#define IDC_APPLY_METADATA              1272
#define IDC_NAME                        1273
#define IDC_FILE_COMMENTS               1274
#define IDC_FOLDER                      1274
#define IDC_CONNECTION_LAN_LABEL        1275
#define IDC_CONNECTION_HOME_LABEL       1276
#define IDC_BROWSE_USER                 1276
#define IDC_RESPECT                     1277
#define IDC_SAVE                        1278
#define IDC_ACTION_0                    1279
#define IDC_ACTION_1                    1280
#define IDC_CLOSE_0                     1280
#define IDC_ACTION_2                    1281
#define IDC_CLOSE_1                     1281
#define IDC_CONNECT_ADVANCED            1281
#define IDC_CLOSE_2                     1282
#define IDC_G2_ENABLE                   1283
#define IDC_G2_SETUP                    1284
#define IDC_ED2K_ENABLE                 1285
#define IDC_ED2K_SETUP                  1286
#define IDC_G1_ENABLE                   1287
#define IDC_ENABLE                      1287
#define IDC_G1_SETUP                    1288
#define IDC_ENABLE_ALWAYS               1288
#define IDC_SERVER_WALK                 1289
#define IDC_RESULTS                     1290
#define IDC_RESULTS_SPIN                1291
#define IDC_LINKS                       1292
#define IDC_IMPORT_DOWNLOADS            1293
#define IDC_PROTOCOLS                   1294
#define IDC_LINKS_SPIN                  1294
#define IDC_MINIMUM_VALUE               1295
#define IDC_DISCOVERY_GO                1295
#define IDC_MINIMUM_CHECK               1296
#define IDC_MAXIMUM_VALUE               1297
#define IDC_MAXIMUM_CHECK               1298
#define IDC_PROTOCOLS_CHECK             1300
#define IDC_PROTOCOLS_LIST              1301
#define IDC_TRANSFERS_MIN               1302
#define IDC_TRANSFERS_MIN_SPIN          1303
#define IDC_CAPACITY                    1304
#define IDC_CAPACITY_SPIN               1305
#define IDC_ROTATE_ENABLE               1306
#define IDC_ROTATE_TIME                 1307
#define IDC_ROTATE_TIME_SPIN            1308
#define IDC_MARKED_CHECK                1309
#define IDC_BANDWIDTH_VALUE             1310
#define IDC_PARTIAL_ENABLE              1311
#define IDC_TRANSFERS_MAX               1312
#define IDC_TRANSFERS_MAX_SPIN          1313
#define IDC_BANDWIDTH_SLIDER            1314
#define IDC_QUEUES                      1315
#define IDC_BANDWIDTH_POINTS            1315
#define IDC_QUEUE_NEW                   1316
#define IDC_REWARD_ENABLE               1316
#define IDC_QUEUE_EDIT                  1317
#define IDC_MATCH_CHECK                 1317
#define IDC_QUEUE_DELETE                1318
#define IDC_UPLOADS_BANDWIDTH_LIMIT     1319
#define IDC_MATCH_TEXT                  1321
#define IDC_FILE_NETWORKS               1322
#define IDC_FILE_TAGS                   1324
#define IDC_LOG                         1327
#define IDC_IMPORT                      1328
#define IDC_CLOSE                       1329
#define IDC_ENABLE_TODAY                1329
#define IDC_TORRENT_FILE                1330
#define IDC_FILTER_LIST                 1331
#define IDC_FILTER_ADD                  1332
#define IDC_FILTER_REMOVE               1333
#define IDC_ICON_LIST                   1334
#define IDC_TORRENT_NAME                1335
#define IDC_TORRENT_TRACKER             1336
#define IDC_TORRENT_FILES               1337
#define IDC_TORRENT_COMPLETED           1338
#define IDC_TORRENT_INCOMPLETE          1339
#define IDC_TORRENT_REFRESH             1340
#define IDC_TORRENT_VIEW                1341
#define IDC_TORRENT_STARTDOWNLOADS      1342
#define IDC_TORRENT_COMMENTS            1343
#define IDC_TORRENT_CREATEDBY           1344
#define IDC_TORRENT_CREATIONDATE        1345
#define IDC_TORRENT_NAME2               1345
#define IDC_RATE_COMMENTS               1346
#define IDC_MESSAGE_AVAILABLE           1347
#define IDC_MESSAGE_DELETED             1348
#define IDC_BANNER                      1349
#define IDC_RATE_VALUE_0                1350
#define IDC_RATE_VALUE_1                1351
#define IDC_RATE_VALUE_2                1352
#define IDC_RATE_VALUE_3                1353
#define IDC_RATE_PROMPT                 1354
#define IDC_DELETE_ALL                  1355
#define IDC_DOWNLOAD                    1357
#define IDC_SEED                        1358
#define IDC_PROFILE_JABBER              1359
#define IDC_URN_SHA1                    1362
#define IDC_URN_TIGER                   1363
#define IDC_URN_ED2K                    1364
#define IDC_TORRENT_INFO                1365
#define IDC_FORGET_VERIFY               1367
#define IDC_FORGET_SOURCES              1368
#define IDC_COMPLETE_AND_VERIFY         1369
#define IDC_ERASE_FROM                  1370
#define IDC_ERASE_TO                    1371
#define IDC_ERASE                       1372
#define IDC_THROTTLE_MODE               1374
#define IDC_REMOTE_ENABLE               1377
#define IDC_REMOTE_USERNAME             1378
#define IDC_REMOTE_PASSWORD             1379
#define IDC_REMOTE_URL                  1380
#define IDC_COLLECTIONS_FOLDER          1381
#define IDC_COLLECTIONS_BROWSE          1382
#define IDC_TORRENTS_FOLDER             1383
#define IDC_TORRENTS_BROWSE             1384
#define IDC_TORRENT_LINKS_SPIN          1385
#define IDC_TORRENT_DEFAULTTRACKER      1386
#define IDC_TORRENT_ENDGAME             1387
#define IDC_TORRENT_INTERFACE           1388
#define IDC_TORRENT_CLIENTLINKS         1389
#define IDC_TORRENT_DOWNLOADS           1390
#define IDC_TORRENT_DOWNLOADS_SPIN      1391
#define IDC_TORRENTS_TORRENTMAKER       1392
#define IDC_TORRENTS_TORRENTMAKERBROWSE 1393
#define IDC_TORRENT_AUTOCLEAR           1394
#define IDC_TORRENT_CLEAR_PERCENTAGE    1395
#define IDC_TORRENT_CLEAR_SPIN          1396
#define IDC_G1_CLIENTMODE               1396
#define IDC_G2_CLIENTMODE               1397
#define IDC_REVIEWS                     1397
#define IDC_REVIEW_FILENAME             1398
#define IDC_CODEPAGES                   1399
#define IDC_SCHEDULER_ENABLE            1400
#define IDC_SCHEDULER_LIMITED           1401
#define IDC_SCHEDULER_LIMITED_SPIN      1402
#define IDC_SCHEDULER_LIMITED_NETWORKS  1403
#define IDC_SCHEDULER_ALLOWHUB          1404
#define IDC_SCHEDULER_DISPLAY           1405
#define IDC_G2_ALWAYS                   1409
#define IDC_FILTERS                     1500
#define IDC_SAVE_FILTER                 1501
#define IDC_SET_DEFAULT_FILTER          1502
#define IDC_DELETE_FILTER               1503
#define IDS_FILTER_DELETE_CONFIRM       7000
#define IDS_SCHEMAS                     7001
#define IDS_MULTIPLE_VALUES             7002
#define IDS_MULTIPLE                    7003
#define IDS_SETTINGS                    8000
#define IDS_WIZARD                      8001
#define IDS_FILE_PROPERTIES             8002
#define IDS_USER_PROFILE                8003
#define IDS_SYSTEM_MESSAGE              8004
#define IDS_CLOSING_AFTER               8005
#define IDS_TABBAR_NOT_CONNECTED        8006
#define IDS_TABBAR_CONNECTED            8007
#define IDS_UPGRADE_LAUNCH              8008
#define IDS_SKIN_DELETE                 8009
#define IDS_BETA_EXPIRED                8010
#define IDS_VIEW_MODE_CONFIRM           8011
#define IDS_STATUS_BAR_CONNECTED_HUB_UP 8060
#define IDS_STATUS_BAR_CONNECTED_UP     8061
#define IDS_STATUS_BAR_CONNECTED_HUB    8062
#define IDS_STATUS_BAR_CONNECTED_SIMPLE 8063
#define IDS_STATUS_BAR_CONNECTED        8064
#define IDS_STATUS_BAR_CONNECTING       8065
#define IDS_STATUS_BAR_DISCONNECTED     8066
#define IDS_STATUS_BAR_BANDWIDTH        8067
#define IDS_TRAY_TIP                    8068
#define IDS_NETWORK_CONNECT             8069
#define IDS_NETWORK_CONNECTING          8070
#define IDS_NETWORK_CONNECTED           8071
#define IDS_NETWORK_DISCONNECT          8072
#define IDS_SEARCH_DETAILS_EMPTY        8096
#define IDS_SEARCH_DETAILS_SOURCES_ONE  8097
#define IDS_SEARCH_DETAILS_SOURCES_MANY 8098
#define IDS_SEARCH_DETAILS_REVIEWS_ONE  8099
#define IDS_SEARCH_DETAILS_REVIEWS_MANY 8100
#define IDS_SEARCH_DETAILS_WRITES       8101
#define IDS_SEARCH_DETAILS_RATES        8102
#define IDS_SEARCH_DETAILS_PREVIEW      8103
#define IDS_SEARCH_DETAILS_PREVIEWING   8104
#define IDS_SEARCH_DETAILS_PREVIEW_FAILED 8105
#define IDS_SEARCH_AGAIN                8128
#define IDS_SEARCH_NONE                 8129
#define IDS_SEARCH_WORKING              8130
#define IDS_SEARCH_EMPTY                8131
#define IDS_SEARCH_FILTERED             8132
#define IDS_SEARCH_ACTIVE               8133
#define IDS_SEARCH_CLEAR_PREVIOUS       8134
#define IDS_SEARCH_NO_METADATA          8135
#define IDS_SEARCH_PLAIN_TEXT           8136
#define IDS_SEARCH_PANEL_SHOW           8141
#define IDS_SEARCH_PANEL_HIDE           8142
#define IDS_SEARCH_PANEL_SEARCHING      8143
#define IDS_SEARCH_PANEL_START          8144
#define IDS_SEARCH_PANEL_MORE           8145
#define IDS_SEARCH_PANEL_STOP           8146
#define IDS_SEARCH_PANEL_AFT            8147
#define IDS_SEARCH_PANEL_INPUT_1        8148
#define IDS_SEARCH_PANEL_INPUT_2        8149
#define IDS_SEARCH_PANEL_RESULTS_STATUS 8150
#define IDS_SEARCH_PANEL_RESULTS_FOUND  8151
#define IDS_SEARCH_PANEL_RESULTS_ACTIVE 8152
#define IDS_SEARCH_PANEL_RESULTS_INACTIVE 8153
#define IDS_SEARCH_PANEL_RESULTS_NONE   8154
#define IDS_SEARCH_PANEL_RESULTS_FORMAT 8155
#define IDS_SEARCH_PANEL_INPUT_CAPTION  8156
#define IDS_SEARCH_PANEL_RESULTS_CAPTION 8157
#define IDS_SEARCH_PANEL_CLEAR          8158
#define IDS_SEARCH_PANEL_ADVANCED       8159
#define IDS_BROWSE_CONNECTING           8160
#define IDS_BROWSE_PUSHED               8161
#define IDS_BROWSE_REQUESTING           8162
#define IDS_BROWSE_DOWNLOADING          8163
#define IDS_BROWSE_CANT_CONNECT         8164
#define IDS_BROWSE_NOT_SUPPORTED        8165
#define IDS_SEARCH_PANEL_INPUT_3        8166
#define IDS_SEARCH_ALL_NETWORKS         8167
#define IDS_SEARCH_PAD_HEADER           8176
#define IDS_SEARCH_PAD_WORDS            8177
#define IDS_SEARCH_PAD_TYPE             8178
#define IDS_SEARCH_PAD_CLEAR_HISTORY    8179
#define IDS_SEARCH_PANEL_INPUT_4        8180
#define IDS_SEARCH_PANEL_INPUT_5        8181
#define IDS_HASH_MESSAGE                8208
#define IDS_DLM_DOWNLOADING             8224
#define IDS_DLM_PAUSED                  8225
#define IDS_DLM_COMPLETED               8226
#define IDS_DLM_TIME_HAM                8227
#define IDS_DLM_TIME_MAS                8228
#define IDS_DLM_TIME_S                  8229
#define IDS_DLM_SOURCING                8230
#define IDS_DLM_NO_SOURCES              8231
#define IDS_DLM_OPEN_OPEN               8232
#define IDS_DLM_OPEN_PREVIEW            8233
#define IDS_DLM_TOTAL_SPEED             8235
#define IDS_DLM_ESTIMATED_TIME          8236
#define IDS_DLM_VOLUME_DOWNLOADED       8237
#define IDS_DLM_NUMBER_OF_SOURCES       8238
#define IDS_DLM_COMPLETED_WORD          8239
#define IDS_DLM_MOVING                  8240
#define IDS_DLM_VERIFY                  8241
#define IDS_DLM_VOLUME_UPLOADED         8243
#define IDS_LIBHEAD_HOME                8288
#define IDS_LIBHEAD_EXPLORE_FOLDER      8289
#define IDS_LIBHEAD_EXPLORE_MANY        8290
#define IDS_LIBPANEL_MULTIPLE_FOLDERS   8291
#define IDS_LIBPANEL_MULTIPLE_FILES     8292
#define IDS_LIBPANEL_NO_SELECTION       8293
#define IDS_LIBPANEL_RECENT_ADDITIONS   8294
#define IDS_LIBPANEL_RATE_FILE          8295
#define IDS_TIP_NA                      8304
#define IDS_TIP_LOCATION                8306
#define IDS_TIP_TYPE                    8307
#define IDS_TIP_SIZE                    8308
#define IDS_TIP_PARTIAL                 8309
#define IDS_TIP_QUEUE                   8310
#define IDS_TIP_EXISTS_LIBRARY          8311
#define IDS_TIP_EXISTS_DOWNLOAD         8312
#define IDS_TIP_BOGUS                   8313
#define IDS_TIP_EXISTS_DELETED          8314
#define IDS_TIP_EXISTS_BLACKLISTED      8315
#define IDS_TIP_HITS                    8316
#define IDS_TIP_UPLOADS                 8317
#define IDS_TIP_TODAYTOTAL              8318
#define IDS_TIP_STATUS                  8320
#define IDS_TIP_SPEED                   8321
#define IDS_TIP_URL                     8322
#define IDS_TIP_USERAGENT               8323
#define IDS_TIP_INACTIVE                8324
#define IDS_TIP_ACTIVE                  8325
#define IDS_TIP_NEXT                    8326
#define IDS_TIP_TOTAL_FILES             8327
#define IDS_TIP_TOTAL_VOLUME            8328
#define IDS_TIP_LIBRARY_PERCENT         8329
#define IDS_TIP_FOLDER                  8330
#define IDS_TIP_SOURCE_BUSY             8331
#define IDS_TIP_SOURCE_FIREWALLED       8332
#define IDS_TIP_SOURCE_UNSTABLE         8333
#define IDS_TIP_FILE_BUSY               8334
#define IDS_TIP_FILE_FIREWALLED         8335
#define IDS_TIP_FILE_UNSTABLE           8336
#define IDS_PROPERTY_PAGE_GENERAL       9000
#define IDS_PROPERTY_PAGE_METADATA      9001
#define IDS_PROPERTY_PAGE_REVIEW        9002
#define IDS_PROPERTY_PAGE_COMMENTS      9002
#define IDS_PROPERTY_PAGE_SHARING       9003
#define IDS_PROPERTY_PAGE_SOURCES       9004
#define IDR_HTML_ABOUT                  12001
#define IDR_HTML_FILENOTFOUND           12002
#define IDR_HTML_HASHMISMATCH           12003
#define IDR_HTML_BUSY                   12004
#define IDR_HTML_BADRANGE               12005
#define IDR_HTML_BROWSER                12006
#define IDR_XML_DEFAULT                 12009
#define IDR_XML_DEFINITIONS             12010
#define IDR_HTML_DISABLED               12011
#define IDS_NETWORK_STARTUP             16064
#define IDS_NETWORK_CANT_LISTEN         16065
#define IDS_NETWORK_DISCONNECTING       16066
#define IDS_NETWORK_DISCONNECTED        16067
#define IDS_NETWORK_LISTENING           16068
#define IDS_NETWORK_LISTENING_TCP       16068
#define IDS_NETWORK_OUTGOING            16069
#define IDS_NETWORK_CANT_OUTGOING       16070
#define IDS_NETWORK_FIREWALLED          16071
#define IDS_NETWORK_LISTENING_UDP       16072
#define IDS_NETWORK_RESOLVING           16073
#define IDS_NETWORK_RESOLVE_FAIL        16074
#define IDS_NETWORK_SECURITY_DENIED     16075
#define IDS_NETWORK_SECURITY_OUTGOING   16076
#define IDS_NETWORK_SECURITY_ALREADY_BLOCKED 16077
#define IDS_NETWORK_SECURITY_BLOCKED    16078
#define IDS_NETWORK_DISCONNECT_CONFIRM  16079
#define IDS_NETWORK_SEARCH_SENT         16081
#define IDS_NETWORK_FORCE_HUB           16083
#define IDS_NETWORK_DISABLE_G1          16084
#define IDS_NETWORK_DISABLE_G2          16085
#define IDS_NETWORK_BANDWIDTH_LOW       16087
#define IDS_CONNECTION_ACCEPTED         16128
#define IDS_CONNECTION_ATTEMPTING       16129
#define IDS_CONNECTION_CONNECT_FAIL     16130
#define IDS_CONNECTION_TIMEOUT_CONNECT  16131
#define IDS_CONNECTION_TIMEOUT_TRAFFIC  16132
#define IDS_CONNECTION_CONNECTED        16133
#define IDS_CONNECTION_CLOSED           16134
#define IDS_CONNECTION_REFUSED          16135
#define IDS_CONNECTION_DROPPED          16136
#define IDS_CONNECTION_ALREADY_REFUSE   16137
#define IDS_CONNECTION_ALREADY_ABORT    16138
#define IDS_CONNECTION_BYE              16139
#define IDS_CONNECTION_CRAWLER          16140
#define IDS_CONNECTION_PEERPRUNE        16141
#define IDS_HANDSHAKE_TIMEOUT           16144
#define IDS_HANDSHAKE_ONLINE            16145
#define IDS_HANDSHAKE_FAIL              16146
#define IDS_HANDSHAKE_BOOTSTRAP         16147
#define IDS_HANDSHAKE_REJECTED          16148
#define IDS_HANDSHAKE_RETRY             16149
#define IDS_HANDSHAKE_SURPLUS           16150
#define IDS_HANDSHAKE_IAMLEAF           16151
#define IDS_HANDSHAKE_CANTBEPEER        16152
#define IDS_HANDSHAKE_BACK2LEAF         16153
#define IDS_HANDSHAKE_GOTPEER           16154
#define IDS_HANDSHAKE_GOTLEAF           16155
#define IDS_HANDSHAKE_NOULTRAPEER       16156
#define IDS_HANDSHAKE_NEEDAPEER         16157
#define IDS_HANDSHAKE_ONLINE_G2         16158
#define IDS_HANDSHAKE_NOTG2             16159
#define IDS_PROTOCOL_TOO_LARGE          16192
#define IDS_PROTOCOL_NO_TTL             16193
#define IDS_PROTOCOL_HIGH_TTL           16194
#define IDS_PROTOCOL_SIZE_PING          16195
#define IDS_PROTOCOL_SIZE_PONG          16196
#define IDS_PROTOCOL_PACKET_DUMP        16197
#define IDS_PROTOCOL_LEAF_FORWARD       16198
#define IDS_PROTOCOL_UNKNOWN            16199
#define IDS_PROTOCOL_ZERO_PONG          16200
#define IDS_PROTOCOL_BAD_QUERY          16201
#define IDS_PROTOCOL_BAD_HIT            16202
#define IDS_PROTOCOL_SIZE_PUSH          16203
#define IDS_PROTOCOL_QRP_UNEXPECTED     16208
#define IDS_PROTOCOL_QRP_FAILED         16209
#define IDS_PROTOCOL_QRP_UPDATED        16210
#define IDS_PROTOCOL_ZERO_PUSH          16211
#define IDS_PROTOCOL_GGEP_REQUIRED      16212
#define IDS_PROTOCOL_QRP_SENT           16213
#define IDS_DOWNLOAD_ADDED              16256
#define IDS_DOWNLOAD_COMPLETED          16257
#define IDS_DOWNLOAD_PAUSED             16258
#define IDS_DOWNLOAD_RESUMED            16259
#define IDS_DOWNLOAD_REMOVE             16260
#define IDS_DOWNLOAD_FILE_CREATE        16261
#define IDS_DOWNLOAD_FILE_CREATE_ERROR  16262
#define IDS_DOWNLOAD_FILE_OPEN_ERROR    16263
#define IDS_DOWNLOAD_CONNECTING         16264
#define IDS_DOWNLOAD_CONNECT_ERROR      16265
#define IDS_DOWNLOAD_CONNECTED          16266
#define IDS_DOWNLOAD_FRAGMENT_REQUEST   16267
#define IDS_DOWNLOAD_FRAGMENT_END       16268
#define IDS_DOWNLOAD_FRAGMENT_OVERLAP   16269
#define IDS_DOWNLOAD_REQUEST_TIMEOUT    16270
#define IDS_DOWNLOAD_TRAFFIC_TIMEOUT    16271
#define IDS_DOWNLOAD_FILENOTFOUND       16272
#define IDS_DOWNLOAD_NOHTTP             16273
#define IDS_DOWNLOAD_HTTPCODE           16274
#define IDS_DOWNLOAD_WRONG_HASH         16275
#define IDS_DOWNLOAD_WRONG_SIZE         16276
#define IDS_DOWNLOAD_WRONG_RANGE        16277
#define IDS_DOWNLOAD_DROPPED            16278
#define IDS_DOWNLOAD_CONTENT            16279
#define IDS_DOWNLOAD_BUSY               16280
#define IDS_DOWNLOAD_CONFIRM_CLEAR      16281
#define IDS_DOWNLOAD_CONFIRM_EXECUTE    16282
#define IDS_DOWNLOAD_DISABLED           16282
#define IDS_DOWNLOAD_ALREADY            16283
#define IDS_DOWNLOAD_BAD_PUSH           16284
#define IDS_DOWNLOAD_UNKNOWN_PUSH       16285
#define IDS_DOWNLOAD_PUSHED             16286
#define IDS_DOWNLOAD_SOURCES_CONNECTED  16287
#define IDS_DOWNLOAD_SOURCES            16288
#define IDS_DOWNLOAD_PUSH_SENT          16289
#define IDS_DOWNLOAD_USEFUL_RANGE       16290
#define IDS_DOWNLOAD_MOVED              16291
#define IDS_DOWNLOAD_CANT_MOVE          16292
#define IDS_DOWNLOAD_RESOLVING          16293
#define IDS_DOWNLOAD_CANT_RESOLVE       16294
#define IDS_DOWNLOAD_BOOST              16295
#define IDS_DOWNLOAD_VERIFY_SUCCESS     16296
#define IDS_DOWNLOAD_VERIFY_FAIL        16297
#define IDS_DOWNLOAD_QUEUED             16298
#define IDS_DOWNLOAD_CONFIRM_CLEAR_PAUSED 16299
#define IDS_DOWNLOAD_CONFIRM_DELETE     16300
#define IDS_DOWNLOAD_TIGER_REQUEST      16301
#define IDS_DOWNLOAD_TIGER_RANGE        16302
#define IDS_DOWNLOAD_TIGER_RECV         16303
#define IDS_DOWNLOAD_TIGER_CORRUPT      16304
#define IDS_DOWNLOAD_TIGER_MISMATCH     16305
#define IDS_DOWNLOAD_TIGER_READY        16306
#define IDS_DOWNLOAD_CLOSING_EXTRA      16307
#define IDS_DOWNLOAD_CLOSING_OVERFLOW   16308
#define IDS_DOWNLOAD_METADATA_REQUEST   16309
#define IDS_DOWNLOAD_METADATA_RECV      16310
#define IDS_DOWNLOAD_HASHSET_REQUEST    16311
#define IDS_DOWNLOAD_HASHSET_ERROR      16312
#define IDS_DOWNLOAD_HASHSET_READY      16313
#define IDS_DOWNLOAD_HASHSET_CORRUPT    16314
#define IDS_DOWNLOAD_INFLATE_ERROR      16315
#define IDS_DOWNLOAD_QUEUE_TIMEOUT      16316
#define IDS_DOWNLOAD_QUEUE_DROP         16317
#define IDS_DOWNLOAD_DISK_SPACE         16318
#define IDS_DOWNLOAD_VERIFY_DROP        16319
#define IDS_UPLOAD_NOHTTP               16320
#define IDS_UPLOAD_CONNECT              16321
#define IDS_UPLOAD_CONNECT_ERROR        16322
#define IDS_UPLOAD_DROPPED              16323
#define IDS_UPLOAD_REQUEST_TIMEOUT      16324
#define IDS_UPLOAD_FILENOTFOUND         16325
#define IDS_UPLOAD_HASH_MISMATCH        16326
#define IDS_UPLOAD_BUSY_OLD             16327
#define IDS_UPLOAD_GIV                  16328
#define IDS_UPLOAD_CANTOPEN             16329
#define IDS_UPLOAD_CONTENT              16330
#define IDS_UPLOAD_FINISHED             16331
#define IDS_UPLOAD_ACCEPTED             16332
#define IDS_UPLOAD_QUEUED               16333
#define IDS_UPLOAD_PUSH_FILENOTFOUND    16334
#define IDS_UPLOAD_REMOVE               16335
#define IDS_UPLOAD_BROWSER              16336
#define IDS_UPLOAD_HEADERS              16337
#define IDS_UPLOAD_BAD_RANGE            16338
#define IDS_UPLOAD_ABOUT                16339
#define IDS_UPLOAD_BROWSE_DENIED        16340
#define IDS_UPLOAD_BROWSE               16341
#define IDS_UPLOAD_TRAFFIC_TIMEOUT      16342
#define IDS_UPLOAD_DROPPED_OLDER        16343
#define IDS_UPLOAD_DROPPED_NEWER        16344
#define IDS_UPLOAD_DELETED              16345
#define IDS_UPLOAD_PARTIAL_CONTENT      16346
#define IDS_UPLOAD_BUSY_FAST            16347
#define IDS_UPLOAD_PUSH_BUSY            16348
#define IDS_UPLOAD_TIGER_SEND           16349
#define IDS_UPLOAD_METADATA_SEND        16350
#define IDS_UPLOAD_BUSY_HOST            16351
#define IDS_UPLOAD_PREVIEW_SEND         16352
#define IDS_UPLOAD_PREVIEW_BUSY         16353
#define IDS_UPLOAD_PREVIEW_EMPTY        16354
#define IDS_UPLOAD_PREVIEW_DYNAMIC      16355
#define IDS_UPLOAD_BROWSE_BUSY          16356
#define IDS_UPLOAD_FILE                 16357
#define IDS_UPLOAD_QUEUE_DROP           16358
#define IDS_UPLOAD_QUEUE_TIMEOUT        16359
#define IDS_UPLOAD_BUSY_QUEUE           16360
#define IDS_UPLOAD_DISABLED             16361
#define IDS_UPLOAD_CANCEL_ED2K          16362
#define IDS_UPLOAD_QUEUE_TORRENT        16363
#define IDS_UPLOAD_QUEUE_HISTORY        16364
#define IDS_DOWNLOAD_CLEAR_GROUP        16365
#define IDS_UPLOAD_QUEUE_QUEUE          16366
#define IDS_UPLOAD_QUEUE_ED2K_CORE      16367
#define IDS_UPLOAD_QUEUE_ED2K_PARTIALS  16368
#define IDS_UPLOAD_QUEUE_ED2K_GUARD     16369
#define IDS_UPLOAD_QUEUE_SMALL_FILES    16370
#define IDS_UPLOAD_QUEUE_MEDIUM_FILES   16371
#define IDS_UPLOAD_QUEUE_LARGE_FILES    16372
#define IDS_UPLOAD_QUEUE_PARTIAL_FILES  16373
#define IDS_UPLOAD_QUEUE_NEW            16374
#define IDS_UPLOAD_QUEUE_PARTIAL        16375
#define IDS_UPLOAD_QUEUE_COMPLETE       16376
#define IDS_UPLOAD_QUEUE_HTTP_GUARD     16377
#define IDS_LIBRARY_CONFIRM_EXECUTE     16384
#define IDS_LIBRARY_METADATA_MANY       16385
#define IDS_LIBRARY_METADATA_EDIT       16386
#define IDS_LIBRARY_BITZI_HASHED        16387
#define IDS_LIBRARY_BITZI_MESSAGE       16388
#define IDS_LIBRARY_DELETE              16389
#define IDS_LIBRARY_ENQUEUE             16390
#define IDS_NEIGHBOURS_NOT_CONNECTED    16391
#define IDS_NEIGHBOURS_CONNECT          16392
#define IDS_LIBRARY_VERIFY_FAIL         16393
#define IDS_LIBRARY_VERIFY_FIX          16394
#define IDS_LIBRARY_DOWNLOADS_ADD       16395
#define IDS_LIBRARY_DOWNLOADS_SHARE     16396
#define IDS_LIBRARY_FOLDER_DELETE       16397
#define IDS_LIBRARY_RENAME_FAIL         16398
#define IDS_LIBRARY_DELETE_FAIL         16399
#define IDS_LIBRARY_TARGET_EXISTS       16400
#define IDS_LIBRARY_TYPE_FILTER_ALL     16401
#define IDS_LIBRARY_COLLECTION_INVALID  16402
#define IDS_LIBRARY_COLLECTION_INSTALLED 16403
#define IDS_LIBRARY_COLLECTION_CANT_INSTALL 16404
#define IDS_LIBRARY_COLLECTION_DOWNLOAD_FILE 16405
#define IDS_LIBRARY_COLLECTION_DOWNLOAD_ALL 16406
#define IDS_LIBRARY_COLLECTION_LOCKDOWN 16407
#define IDS_LIBRARY_COPYURI             16408
#define IDS_LIBRARY_EXPORTURIS          16409
#define IDS_CHAT_CONNECTED_X            16448
#define IDS_CHAT_ONLINE_X               16449
#define IDS_CHAT_CLOSED_X               16450
#define IDS_CHAT_DROPPED_X              16451
#define IDS_CHAT_UNRECOGNISED_X         16452
#define IDS_CHAT_CONNECTING_X           16453
#define IDS_CHAT_ACCEPTED_X             16454
#define IDS_CHAT_NICK_X                 16455
#define IDS_CHAT_CONNECT_FAIL_X         16456
#define IDS_CHAT_PROTOCOL_X             16457
#define IDS_CHAT_RESPONSE_X             16458
#define IDS_CHAT_UNCONNECTED_X          16459
#define IDS_GRAPH_TOTAL_BANDWIDTH_IN    16512
#define IDS_GRAPH_TOTAL_BANDWIDTH_OUT   16513
#define IDS_GRAPH_GNUTELLA_CONNECTIONS  16514
#define IDS_GRAPH_GNUTELLA_CONNECTIONS_ALL 16515
#define IDS_GRAPH_GNUTELLA_BANDWIDTH_IN 16516
#define IDS_GRAPH_GNUTELLA_BANDWIDTH_OUT 16517
#define IDS_GRAPH_DOWNLOADS_FILES       16518
#define IDS_GRAPH_DOWNLOADS_TRANSFERS   16519
#define IDS_GRAPH_DOWNLOADS_BANDWIDTH   16520
#define IDS_GRAPH_UPLOADS_TRANSFERS     16521
#define IDS_GRAPH_UPLOADS_BANDWIDTH     16522
#define IDS_GRAPH_GNUTELLA_PACKETS_IN   16523
#define IDS_GRAPH_GNUTELLA_PACKETS_OUT  16524
#define IDS_GRAPH_GNUTELLA_ROUTED       16525
#define IDS_GRAPH_GNUTELLA_DROPPED      16526
#define IDS_GRAPH_GNUTELLA_LOST         16527
#define IDS_GRAPH_GNUTELLA_QUERIES      16528
#define IDS_GRAPH_TOTAL_BANDWIDTH_TCP_IN 16532
#define IDS_GRAPH_TOTAL_BANDWIDTH_TCP_OUT 16533
#define IDS_GRAPH_TOTAL_BANDWIDTH_UDP_IN 16534
#define IDS_GRAPH_TOTAL_BANDWIDTH_UDP_OUT 16535
#define IDS_URL_RECEIVED                16768
#define IDS_URL_PARSE_ERROR             16769
#define IDS_URL_BUSY                    16770
#define IDS_URL_ALREADY_HAVE            16771
#define IDS_URL_HOST                    16772
#define IDS_URL_PORT                    16773
#define IDS_URL_CONNECT                 16774
#define IDS_URL_BROWSE                  16775
#define IDS_URL_ADD                     16776
#define IDS_URL_FILENAME                16777
#define IDS_URL_URL                     16778
#define IDS_URL_TYPE                    16779
#define IDS_URL_UNSPECIFIED             16780
#define IDS_BITZI_REQUESTING            16781
#define IDS_BITZI_SUCCESS               16782
#define IDS_BITZI_FINISHED              16783
#define IDS_BITZI_CLOSE                 16784
#define IDS_MEDIAVIS_NOVIS              16785
#define IDS_WIZARD_NEED_SPEED           16800
#define IDS_WIZARD_NEED_CONNECTION      16801
#define IDS_WIZARD_SHARE_CONFIRM        16802
#define IDS_WIZARD_SHARE_ALREADY        16803
#define IDS_PROFILE_NO_NICK             16804
#define IDS_PROFILE_NO_LOCATION         16805
#define IDS_WIZARD_PORT_FORWARD         16806
#define IDS_SETTINGS_NEED_BANDWIDTH     16807
#define IDS_PROFILE_NO_VITALS           16808
#define IDS_WIZARD_EXIT                 16809
#define IDS_WIZARD_YEARS_OLD            16810
#define IDS_SETTINGS_AUTOMATIC_IP       16811
#define IDS_SETTINGS_WARN_QUEUELIMIT    16816
#define IDS_DISCOVERY_BOOTSTRAP         16864
#define IDS_DISCOVERY_QUERY             16865
#define IDS_DISCOVERY_WEB_SUCCESS       16866
#define IDS_DISCOVERY_FAILED            16867
#define IDS_DISCOVERY_FAIL_REMOVE       16868
#define IDS_DISCOVERY_DEFAULTS          16869
#define IDS_DISCOVERY_UPDATING          16870
#define IDS_DISCOVERY_SUBMIT            16871
#define IDS_BROWSE_CONNECTING_TO        16928
#define IDS_BROWSE_CANT_CONNECT_TO      16929
#define IDS_BROWSE_PUSHED_TO            16930
#define IDS_BROWSE_CANT_PUSH_TO         16931
#define IDS_BROWSE_SENT_REQUEST         16932
#define IDS_BROWSE_NOT_HTTP             16933
#define IDS_BROWSE_HTTPCODE             16934
#define IDS_BROWSE_BAD_RESPONSE         16935
#define IDS_BROWSE_DOWNLOADING_FROM     16936
#define IDS_BROWSE_PACKET_ERROR         16938
#define IDS_BROWSE_FINISHED             16939
#define IDS_BROWSE_DROPPED              16940
#define IDS_BROWSE_TIMEOUT              16941
#define IDS_BROWSE_CLOSED               16942
#define IDS_BROWSE_TITLE_FORMAT         16943
#define IDS_BROWSE_INTRO_FORMAT         16944
#define IDS_MEDIA_PLUGIN_CREATE         16992
#define IDS_MEDIA_FILTER                16993
#define IDS_MEDIA_LOAD_FAIL             16994
#define IDS_MEDIA_LOAD_FAIL_HELP        16995
#define IDS_MEDIA_PARTIAL_RENDER        16996
#define IDS_MEDIA_EMPTY                 16997
#define IDS_MEDIA_TITLE                 16998
#define IDS_MEDIA_PLAYLIST              16999
#define IDS_CHAT_CONNECTING_TO          17024
#define IDS_CHAT_CANT_CONNECT           17025
#define IDS_CHAT_PUSH_SENT              17026
#define IDS_CHAT_PUSH_DONE              17027
#define IDS_CHAT_CONNECTED              17028
#define IDS_CHAT_HANDSHAKE_FAIL         17029
#define IDS_CHAT_HANDSHAKE_G1           17030
#define IDS_CHAT_HANDSHAKE_G2           17031
#define IDS_CHAT_PROFILE_ACCEPTED       17032
#define IDS_CHAT_PRIVATE_START          17033
#define IDS_CHAT_PRIVATE_ONLINE         17034
#define IDS_CHAT_PRIVATE_REFUSED        17035
#define IDS_CHAT_PRIVATE_AWAY           17036
#define IDS_CHAT_DROPPED                17037
#define IDS_CHAT_CLOSED                 17038
#define IDS_CHAT_CANT_PUSH              17039
#define IDS_CHAT_NOT_CONNECTED_1        17040
#define IDS_CHAT_NOT_CONNECTED_2        17041
#define IDS_CHAT_NEED_PROFILE           17042
#define IDS_CHAT_PRIORITY_GRANTED       17043
#define IDS_NEIGHBOUR_G1PP              17100
#define IDS_NEIGHBOUR_G1LU              17101
#define IDS_NEIGHBOUR_G1UL              17102
#define IDS_NEIGHBOUR_G2HH              17103
#define IDS_NEIGHBOUR_G2LH              17104
#define IDS_NEIGHBOUR_G2HL              17105
#define IDS_NEIGHBOUR_ED2K_LOW          17106
#define IDS_NEIGHBOUR_ED2K_HIGH         17107
#define IDS_NEIGHBOUR_HANDSHAKE         17108
#define IDS_NEIGHBOUR_INBOUND           17109
#define IDS_NEIGHBOUR_OUTBOUND          17110
#define IDS_NEIGHBOUR_CURRENT           17111
#define IDS_NEIGHBOUR_TOTAL             17112
#define IDS_NEIGHBOUR_COMPRESSION       17113
#define IDS_NEIGHBOUR_RATIO             17114
#define IDS_NEIGHBOUR_COMPRESSION_DF    17115
#define IDS_NEIGHBOUR_COMPRESSION_NONE  17116
#define IDS_NEIGHBOUR_CONNECTING        17117
#define IDS_NEIGHBOUR_HANDSHAKING       17118
#define IDS_NEIGHBOUR_REJECTED          17119
#define IDS_NEIGHBOUR_CLOSING           17120
#define IDS_NEIGHBOUR_UNKNOWN           17121
#define IDS_NEIGHBOUR_G1PEER            17122
#define IDS_NEIGHBOUR_G1ULTRA           17123
#define IDS_NEIGHBOUR_G1LEAF            17124
#define IDS_NEIGHBOUR_G2PEER            17125
#define IDS_NEIGHBOUR_G2HUB             17126
#define IDS_NEIGHBOUR_G2LEAF            17127
#define IDS_NEIGHBOUR_ED2K_SERVER       17128
#define IDS_NEIGHBOUR_ED2K_LOWID        17129
#define IDS_NEIGHBOUR_ED2K_HIGHID       17130
#define IDS_ED2K_SERVER_CONNECTING      17216
#define IDS_ED2K_SERVER_CONNECTED       17217
#define IDS_ED2K_SERVER_MESSAGE         17218
#define IDS_ED2K_SERVER_REFUSED         17219
#define IDS_ED2K_SERVER_ONLINE          17220
#define IDS_ED2K_SERVER_IDCHANGE        17221
#define IDS_ED2K_SERVER_IDENT           17222
#define IDS_ED2K_SERVER_REJECTED        17223
#define IDS_ED2K_CLIENT_HANDSHAKE_FAIL  17224
#define IDS_ED2K_CLIENT_DROPPED         17225
#define IDS_ED2K_CLIENT_BAD_PACKET      17226
#define IDS_ED2K_CLIENT_ACCEPTED        17227
#define IDS_ED2K_CLIENT_SENT_HASHSET    17228
#define IDS_ED2K_CLIENT_CLOSED          17229
#define IDS_ED2K_CLIENT_CONNECTING      17230
#define IDS_ED2K_CLIENT_WRONG_GUID      17231
#define IDS_ED2K_CLIENT_CONNECT_TIMEOUT 17232
#define IDS_ED2K_CLIENT_HANDSHAKE_TIMEOUT 17233
#define IDS_ED2K_CLIENT_DISABLED        17234
#define IDS_ED2K_EPI_START              17248
#define IDS_ED2K_EPI_FINISHED           17249
#define IDS_ED2K_EPI_FOLDER             17250
#define IDS_ED2K_EPI_FILE_FAILED        17251
#define IDS_ED2K_EPI_FILE_START         17252
#define IDS_ED2K_EPI_CANT_OPEN_PART     17253
#define IDS_ED2K_EPI_DETECTED           17254
#define IDS_ED2K_EPI_FILE_OLD           17255
#define IDS_ED2K_EPI_COPY_START         17256
#define IDS_ED2K_EPI_COPY_FINISHED      17257
#define IDS_ED2K_EPI_FILE_CREATED       17258
#define IDS_ED2K_EPI_ALREADY            17259
#define IDS_ED2K_EPI_DISK_SPACE         17260
#define IDS_BT_CLIENT_ACCEPTED          17472
#define IDS_BT_CONNECT_TIMEOUT          17473
#define IDS_BT_CLIENT_CONNECT_TIMEOUT   17473
#define IDS_BT_HANDSHAKE_TIMEOUT        17474
#define IDS_BT_CLIENT_HANDSHAKE_TIMEOUT 17474
#define IDS_BT_CLIENT_LOST              17475
#define IDS_BT_CLIENT_WRONG_GUID        17476
#define IDS_BT_CLIENT_WRONG_FILE        17477
#define IDS_BT_CLIENT_UNKNOWN_FILE      17478
#define IDS_BT_CLIENT_ONLINE            17479
#define IDS_BT_CLIENT_DROPPED           17480
#define IDS_BT_PREFETCH_FILE            17481
#define IDS_BT_PREFETCH_ERROR           17482
#define IDS_BT_TRACK_ERROR              17483
#define IDS_BT_TRACK_PARSE_ERROR        17484
#define IDS_BT_TRACK_SUCCESS            17485
#define IDS_BT_CLIENT_CONNECTING        17486
#define IDS_BT_CLIENT_HANDSHAKING       17487
#define IDS_BT_TRACK_CHANGE             17488
#define IDS_BT_CLIENT_EXTENDED          17489
#define IDS_BT_CLIENT_EXCHANGE          17490
#define IDS_BT_SEED_ALREADY             17491
#define IDS_BT_SEED_PARSE_ERROR         17492
#define IDS_BT_SEED_CREATE_FAIL         17493
#define IDS_BT_SEED_SOURCE_LOST         17494
#define IDS_BT_SEED_SOURCE_SIZE         17495
#define IDS_BT_SEED_COPY_FAIL           17496
#define IDS_BT_SEED_ERROR               17497
#define IDS_BT_SEED_VERIFY_FAIL         17498
#define IDS_DOWNLOAD_EDIT_RENAME        18496
#define IDS_DOWNLOAD_EDIT_BAD_SHA1      18497
#define IDS_DOWNLOAD_EDIT_BAD_TIGER     18498
#define IDS_DOWNLOAD_EDIT_BAD_ED2K      18499
#define IDS_DOWNLOAD_EDIT_CHANGE_SHA1   18500
#define IDS_DOWNLOAD_EDIT_CHANGE_TIGER  18501
#define IDS_DOWNLOAD_EDIT_CHANGE_ED2K   18502
#define IDS_DOWNLOAD_EDIT_FORGET_VERIFY 18503
#define IDS_DOWNLOAD_EDIT_FORGET_SOURCES 18504
#define IDS_DOWNLOAD_EDIT_BAD_RANGE     18505
#define IDS_DOWNLOAD_EDIT_CANT_ERASE    18506
#define IDS_DOWNLOAD_EDIT_ERASED        18507
#define IDS_DOWNLOAD_QUEUE_HUGE         18508
#define IDS_DOWNLOAD_EDIT_COMPLETE_NOHASH 18509
#define IDS_DOWNLOAD_EDIT_COMPLETE_VERIFY 18510
#define IDS_REMOTE_DISABLED             19000
#define IDS_REMOTE_ENABLED              19001
#define IDS_REMOTE_UNAVAILABLE          19002
#define IDS_GENERAL_NOURNAVAILABLE      20000
#define IDS_GENERAL_CLOSE               20001
#define IDS_GENERAL_OF                  20002
#define IDS_STATUS_CONNECTING           20100
#define IDS_STATUS_REQUESTING           20101
#define IDS_STATUS_RESPONSE             20102
#define IDS_STATUS_DOWNLOADING          20103
#define IDS_STATUS_TIGERTREE            20104
#define IDS_STATUS_HASHSET              20105
#define IDS_STATUS_METADATA             20106
#define IDS_STATUS_BUSY                 20107
#define IDS_STATUS_ENQUEUE              20108
#define IDS_STATUS_QUEUED               20109
#define IDS_STATUS_UNKNOWN              20110
#define IDS_STATUS_COMPLETED            20111
#define IDS_STATUS_SEEDING              20112
#define IDS_STATUS_MOVING               20113
#define IDS_STATUS_PAUSED               20114
#define IDS_STATUS_FILEERROR            20115
#define IDS_STATUS_CANTMOVE             20116
#define IDS_STATUS_VERIFYING            20117
#define IDS_STATUS_ACTIVE               20118
#define IDS_STATUS_PENDING              20119
#define IDS_STATUS_SEARCHING            20120
#define IDS_STATUS_CREATING             20121
#define IDS_STATUS_TORRENT              20122
#define IDS_STATUS_TRACKERDOWN          20123
#define IDS_STATUS_NOSOURCES            20124
#define IDS_STATUS_VERIFIED             20125
#define IDS_STATUS_UNVERIFIED           20126
#define IDS_STATUS_SOURCE               20127
#define IDS_STATUS_SOURCES              20128
#define IDS_STATUS_SOURCESTENS          20129
#define IDS_STATUS_SOURCES11TO19        20130
#define IDS_STATUS_SOURCES2TO4          20131
#define IDS_STATUS_SOURCES5TO9          20132
#define IDS_STATUS_UNINTERESTED         20133
#define IDS_STATUS_CHOKED               20134
#define IDS_STATUS_NEXT                 20135
#define IDS_STATUS_Q                    20136
#define IDS_DAY_SUNDAY                  20200
#define IDS_DAY_MONDAY                  20201
#define IDS_DAY_TUESDAY                 20202
#define IDS_DAY_WEDNESDAY               20203
#define IDS_DAY_THURSDAY                20204
#define IDS_DAY_FRIDAY                  20205
#define IDS_DAY_SATURDAY                20206
#define IDS_RATING_NORATING             20210
#define IDS_RATING_1                    20211
#define IDS_RATING_2                    20212
#define IDS_RATING_3                    20213
#define IDS_RATING_4                    20214
#define IDS_RATING_5                    20215
#define IDS_RATING_6                    20216
#define ID_HELP_ABOUT                   32772
#define ID_CHECKMARK                    32774
#define ID_NETWORK_EXIT                 32776
#define ID_NETWORK_CONNECT              32777
#define ID_NETWORK_DISCONNECT           32778
#define ID_TOOLS_SETTINGS               32779
#define ID_VIEW_SYSTEM                  32782
#define ID_VIEW_NEIGHBOURS              32783
#define ID_VIEW_TRAFFIC                 32784
#define ID_VIEW_LIBRARY                 32785
#define ID_VIEW_DOWNLOADS               32786
#define ID_VIEW_UPLOADS                 32787
#define ID_VIEW_HOSTS                   32788
#define ID_VIEW_PACKETS                 32789
#define ID_NEIGHBOURS_DISCONNECT        32790
#define ID_SYSTEM_CLEAR                 32791
#define ID_NEIGHBOURS_VIEW_ALL          32793
#define ID_NEIGHBOURS_VIEW_INCOMING     32794
#define ID_NEIGHBOURS_VIEW_OUTGOING     32795
#define ID_VIEW_SEARCH_MONITOR          32796
#define ID_VIEW_RESULTS_MONITOR         32797
#define ID_HOSTCACHE_CONNECT            32798
#define ID_HOSTCACHE_DISCONNECT         32799
#define ID_HOSTCACHE_REMOVE             32800
#define ID_NETWORK_CONNECT_TO           32801
#define ID_NETWORK_SEARCH               32807
#define ID_SEARCH_DOWNLOAD              32808
#define ID_SEARCH_SEARCH                32809
#define ID_SEARCH_FILTER                32810
#define ID_SEARCH_FILTER_REMOVE         32811
#define ID_HITMONITOR_CLEAR             32813
#define ID_SEARCHMONITOR_PAUSE          32814
#define ID_HITMONITOR_PAUSE             32815
#define ID_SEARCHMONITOR_CLEAR          32816
#define ID_SEARCH_COPY                  32817
#define ID_HITMONITOR_SEARCH            32819
#define ID_HOSTCACHE_G2_HORIZON         32820
#define ID_HOSTCACHE_G2_CACHE           32821
#define ID_HOSTCACHE_G1_CACHE           32822
#define ID_SEARCH_COLUMNS               32823
#define ID_SEARCH_DOWNLOADNOW           32824
#define ID_DOWNLOADS_RESUME             32826
#define ID_DOWNLOADS_CLEAR_COMPLETED    32828
#define ID_DOWNLOADS_SOURCES            32829
#define ID_DOWNLOADS_LAUNCH             32830
#define ID_DOWNLOADS_CLEAR              32831
#define ID_DOWNLOADS_PAUSE              32832
#define ID_DOWNLOADS_VIEW_REVIEWS       32833
#define ID_LIBRARY_EXPLORE              32834
#define ID_LIBRARY_SCAN                 32835
#define ID_LIBRARY_SHARED_FILE          32836
#define ID_LIBRARY_REMOVE               32837
#define ID_LIBRARY_ADD                  32838
#define ID_LIBRARY_PROPERTIES           32839
#define ID_LIBRARY_COLUMNS              32840
#define ID_DOWNLOADS_CLEAR_PAUSED       32842
#define ID_UPLOADS_LAUNCH               32843
#define ID_UPLOADS_DISCONNECT           32844
#define ID_UPLOADS_CLEAR_COMPLETED      32845
#define ID_UPLOADS_CLEAR                32846
#define ID_UPLOADS_EDIT_QUEUE           32847
#define ID_TRANSFERS_DISCONNECT         32848
#define ID_TRANSFERS_FORGET             32849
#define ID_UPLOADS_HELP                 32850
#define ID_HELP_HOMEPAGE                32851
#define ID_HELP_WEB_1                   32852
#define ID_HELP_WEB_2                   32853
#define ID_HELP_WEB_3                   32854
#define ID_HELP_FAQ                     32855
#define ID_SEARCH_CHAT                  32860
#define ID_TRAFFIC_GRID                 32862
#define ID_TRAFFIC_AXIS                 32863
#define ID_TRAFFIC_LEGEND               32864
#define ID_TRAFFIC_SETUP                32865
#define ID_TRAFFIC_CLEAR                32866
#define ID_TOOLS_WIZARD                 32867
#define ID_CHILD_RESTORE                32869
#define ID_CHILD_CLOSE                  32870
#define ID_CHILD_MAXIMISE               32871
#define ID_CHILD_MINIMISE               32872
#define ID_TRANSFERS_CHAT               32876
#define ID_UPLOADS_CHAT                 32877
#define ID_SEARCH_CLEAR                 32878
#define ID_TRAY_OPEN                    32879
#define ID_NETWORK_AUTO_CLOSE           32881
#define ID_UPLOADS_AUTO_CLEAR           32882
#define ID_LIBRARY_SEARCH               32883
#define ID_TRAFFIC_WINDOW               32884
#define ID_NEIGHBOURS_CHAT              32885
#define ID_HELP_WEB_4                   32886
#define ID_HELP_WEB_5                   32887
#define ID_HELP_WEB_6                   32888
#define ID_SEARCH_STOP                  32889
#define ID_TOOLS_DOWNLOAD               32890
#define ID_DOWNLOADS_URL                32891
#define ID_LIBRARY_BITZI_WEB            32892
#define ID_LIBRARY_BITZI_DOWNLOAD       32893
#define ID_VIEW_SECURITY                32895
#define ID_SECURITY_EDIT                32896
#define ID_SECURITY_REMOVE              32897
#define ID_SECURITY_RESET               32898
#define ID_SECURITY_ADD                 32899
#define ID_SECURITY_POLICY_ACCEPT       32900
#define ID_SECURITY_POLICY_DENY         32901
#define ID_LIBRARY_REFRESH              32902
#define ID_LIBRARY_MOVE                 32904
#define ID_LIBRARY_COPY                 32905
#define ID_LIBRARY_DELETE               32906
#define ID_LIBRARY_ENQUEUE              32909
#define ID_DOWNLOADS_ENQUEUE            32910
#define ID_SECURITY_MOVE_UP             32912
#define ID_SECURITY_MOVE_DOWN           32913
#define ID_SECURITY_BAN                 32914
#define ID_TAB_NETWORK                  32918
#define ID_TAB_LIBRARY                  32919
#define ID_TAB_TRANSFERS                32920
#define ID_TAB_CONNECT                  32921
#define ID_VIEW_TABBED                  32922
#define ID_VIEW_WINDOWED                32923
#define ID_LIBRARY_URL                  32924
#define ID_VIEW_DISCOVERY               32925
#define ID_DISCOVERY_EDIT               32927
#define ID_DISCOVERY_QUERY              32928
#define ID_DISCOVERY_REMOVE             32929
#define ID_DISCOVERY_ADD                32930
#define ID_DISCOVERY_BLOCKED			32931
#define ID_DISCOVERY_GNUTELLA           32932
#define ID_DISCOVERY_WEBCACHE           32933
#define ID_DOWNLOADS_AUTO_CLEAR         32934
#define ID_TRANSFERS_CONNECT            32935
#define ID_DOWNLOADS_SHOW_SOURCES       32936
#define ID_SYSTEM_VERBOSE               32937
#define ID_DISCOVERY_ADVERTISE          32938
#define ID_DISCOVERY_BROWSE             32939
#define ID_BROWSE_STOP                  32940
#define ID_BROWSE_REFRESH               32941
#define ID_BROWSE_LAUNCH                32943
#define ID_DOWNLOADS_BOOST              32944
#define ID_TAB_HOME                     32946
#define ID_DOWNLOADS_LAUNCH_COPY        32947
#define ID_DOWNLOADS_MONITOR            32949
#define ID_LIBRARY_SELECT_ALL           32950
#define ID_SECURITY_EXPORT              32951
#define ID_SECURITY_IMPORT              32952
#define ID_SEARCH_FILTER_RAW            32953
#define ID_SEARCH_PANEL                 32954
#define ID_SYSTEM_TIMESTAMP             32956
#define ID_LIBRARY_LAUNCH               32957
#define ID_NEIGHBOURS_COPY              32958
#define ID_TOOLS_RESKIN                 32959
#define ID_MONITOR_CLOSE                32960
#define ID_WINDOW_TOOLBAR               32961
#define ID_WINDOW_TABBAR                32962
#define ID_WINDOW_MONITOR               32963
#define ID_NETWORK_BROWSE_TO            32964
#define ID_TOOLS_SKIN                   32965
#define ID_LIBRARY_HASH_PRIORITY        32967
#define ID_DOWNLOADS_FILE_DELETE        32968
#define ID_LIBRARY_RENAME               32970
#define ID_UPLOADS_START                32971
#define ID_DOWNLOADS_MOVE_UP            32972
#define ID_DOWNLOADS_MOVE_DOWN          32973
#define ID_TOOLS_LANGUAGE               32974
#define ID_DOWNLOADS_SETTINGS           32975
#define ID_UPLOADS_SETTINGS             32976
#define ID_DOWNLOADS_FILTER_ALL         32977
#define ID_DOWNLOADS_FILTER_ACTIVE      32978
#define ID_DOWNLOADS_FILTER_QUEUED      32979
#define ID_DOWNLOADS_FILTER_SOURCES     32980
#define ID_DOWNLOADS_FILTER_PAUSED      32981
#define ID_NEIGHBOURS_SETTINGS          32982
#define ID_LIBRARY_TREE_PHYSICAL        32983
#define ID_LIBRARY_TREE_VIRTUAL         32984
#define ID_LIBRARY_SHARED_FOLDER        32985
#define ID_LIBRARY_VIEW                 32986
#define ID_LIBRARY_VIEW_DETAIL          32987
#define ID_LIBRARY_VIEW_HOME            32988
#define ID_LIBRARY_VIEW_LIST            32989
#define ID_LIBRARY_VIEW_ICON            32990
#define ID_LIBRARY_VIEW_THUMBNAIL       32991
#define ID_LIBRARY_PARENT               32992
#define ID_LIBRARY_PANEL                32993
#define ID_LIBRARY_FOLDER_PROPERTIES    32994
#define ID_LIBRARY_FOLDER_DELETE        32995
#define ID_LIBRARY_FOLDER_NEW           32996
#define ID_LIBRARY_UNLINK               32997
#define ID_LIBRARY_FOLDER_METADATA      32998
#define ID_VIEW_MEDIA                   32999
#define ID_TAB_MEDIA                    33000
#define ID_MEDIA_OPEN                   33001
#define ID_MEDIA_CLOSE                  33002
#define ID_MEDIA_PLAY                   33003
#define ID_MEDIA_STOP                   33004
#define ID_MEDIA_PREVIOUS               33005
#define ID_MEDIA_NEXT                   33006
#define ID_MEDIA_SIZE_FILL              33007
#define ID_MEDIA_SIZE_DISTORT           33008
#define ID_MEDIA_SIZE_ONE               33009
#define ID_MEDIA_SIZE_TWO               33010
#define ID_MEDIA_SIZE_THREE             33011
#define ID_MEDIA_FULLSCREEN             33012
#define ID_MEDIA_RANDOM                 33013
#define ID_MEDIA_REPEAT                 33014
#define ID_MEDIA_SETTINGS               33015
#define ID_MEDIA_PAUSE                  33016
#define ID_MEDIA_ZOOM                   33017
#define ID_MEDIA_ASPECT_DEFAULT         33018
#define ID_MEDIA_ASPECT_4_3             33019
#define ID_MEDIA_ASPECT_16_9            33020
#define ID_MEDIA_SELECT                 33021
#define ID_MEDIA_ADD                    33022
#define ID_MEDIA_REMOVE                 33023
#define ID_MEDIA_CLEAR                  33024
#define ID_MEDIA_SAVE                   33025
#define ID_MEDIA_PLAYLIST               33027
#define ID_LIBRARY_VIEW_TILE            33028
#define ID_LIBRARY_ALBUM_OPEN           33029
#define ID_LIBRARY_FOLDER_ENQUEUE       33030
#define ID_LIBRARY_ALBUM_DELETE         33031
#define ID_LIBRARY_ALBUM_PROPERTIES     33032
#define ID_TAB_SEARCH                   33033
#define ID_LIBRARY_FOLDERS              33034
#define ID_TOOLS_PROFILE                33035
#define ID_BROWSE_PROFILE               33036
#define ID_BROWSE_FILES                 33037
#define ID_MEDIA_VIS                    33040
#define ID_SYSTEM_TEST                  33041
#define ID_DOWNLOADS_LAUNCH_COMPLETE    33042
#define ID_CHAT_CONNECT                 33043
#define ID_CHAT_DISCONNECT              33044
#define ID_CHAT_BROWSE                  33045
#define ID_CHAT_COLOUR                  33046
#define ID_CHAT_BOLD                    33047
#define ID_CHAT_ITALIC                  33048
#define ID_CHAT_UNDERLINE               33049
#define ID_CHAT_SEND_FILE               33050
#define ID_CHAT_PRIORITY                33051
#define ID_CHAT_CLEAR                   33052
#define ID_CHAT_EMOTICONS               33053
#define ID_DOWNLOADS_SHARE              33054
#define ID_MEDIA_ADD_FOLDER             33055
#define ID_LIBRARY_FOLDER_FILE_PROPERTIES 33056
#define ID_LIBRARY_REBUILD              33057
#define ID_VIEW_HELP                    33058
#define ID_TAB_HELP                     33059
#define ID_DOWNLOADS_COPY               33060
#define ID_LIBRARY_VIEW_ALBUM           33061
#define ID_SEARCH_DETAILS               33062
#define ID_HELP_WARNINGS                33063
#define ID_HELP_PROMOTE                 33064
#define ID_UPLOADS_FILTER_ALL           33065
#define ID_UPLOADS_FILTER_ACTIVE        33066
#define ID_UPLOADS_FILTER_QUEUED        33067
#define ID_UPLOADS_FILTER_HISTORY       33068
#define ID_SEARCH_FOR_THIS              33069
#define ID_SEARCH_FOR_SIMILAR           33070
#define ID_SEARCH_FOR_ARTIST            33071
#define ID_SEARCH_FOR_ALBUM             33072
#define ID_SEARCH_FOR_SERIES            33073
#define ID_CHAT_TIMESTAMP               33074
#define ID_MEDIA_STATUS                 33075
#define ID_HOSTCACHE_ED2K_CACHE         33076
#define ID_HOSTCACHE_IMPORT             33077
#define ID_HOSTCACHE_ED2K_DOWNLOAD      33078
#define ID_DISCOVERY_SERVERMET          33079
#define ID_NETWORK_G2                   33080
#define ID_NETWORK_G1                   33081
#define ID_NETWORK_ED2K                 33082
#define ID_NETWORK_HTTP                 33083
#define ID_NETWORK_FTP                  33084
#define ID_NETWORK_BT                   33085
#define ID_HOSTCACHE_PRIORITY           33086
#define ID_VIEW_BASIC                   33087
#define ID_LIBRARY_SEARCH_QUICK         33088
#define ID_DOWNLOAD_GROUP_NEW           33089
#define ID_DOWNLOAD_GROUP_REMOVE        33090
#define ID_DOWNLOAD_GROUP_PROPERTIES    33091
#define ID_DOWNLOAD_GROUP_PAUSE         33092
#define ID_DOWNLOAD_GROUP_RESUME        33093
#define ID_DOWNLOAD_GROUP_CLEAR         33094
#define ID_DOWNLOADS_TORRENT_INFO       33095
#define ID_DOWNLOAD_GROUP_SHOW          33096
#define ID_DOWNLOADS_HELP               33097
#define ID_DOWNLOADS_FILTER_MENU        33098
#define ID_UPLOADS_FILTER_MENU          33099
#define ID_DOWNLOADS_CLEAR_INCOMPLETE   33100
#define ID_DOWNLOADS_CLEAR_COMPLETE     33101
#define ID_LIBRARY_CREATETORRENT        33102
#define ID_WINDOW_NAVBAR                33104
#define ID_DOWNLOADS_RATE               33105
#define ID_LIBRARY_VIEW_COLLECTION      33106
#define ID_LIBRARY_FOLDER_DOWNLOAD      33107
#define ID_LIBRARY_FOLDER_EXPORT_COLLECTION 33108
#define ID_LIBRARY_EXPORT_COLLECTION    33109
#define ID_LIBRARY_SEED_TORRENT         33110
#define ID_LIBRARY_REBUILD_ANSI         33111
#define ID_DOWNLOADS_EDIT               33112
#define ID_MEDIA_MUTE                   33113
#define ID_WINDOW_REMOTE                33114
#define ID_UPLOADS_FILTER_TORRENT       33115
#define ID_TOOLS_MERCORA                33116
#define ID_HELP_FIREWALLS               33117
#define ID_TOOLS_SEEDTORRENT            33118
#define ID_HELP_SECURITY                33119
#define ID_HELP_FORUMS                  33120
#define ID_TOOLS_RESEEDTORRENT          33121
#define ID_HELP_DISKSPACE               33130
#define ID_HELP_DISKWRITEFAIL           33131
#define ID_HELP_CONNECTIONFAIL          33132
#define ID_HELP_DONKEYSERVERS           33134

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        270
#define _APS_NEXT_COMMAND_VALUE         33135
#define _APS_NEXT_CONTROL_VALUE         1412
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
