//
// VirusTotal.idl : IDL source for VirusTotal
//
// Copyright (c) Nikolay Raspopov, 2009-2010.
// This file is part of SHAREAZA (shareaza.sourceforge.net)
//
// Shareaza is free software; you can redistribute it
// and/or modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2 of
// the License, or (at your option) any later version.
//
// Shareaza is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Shareaza; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
//

import "oaidl.idl";
import "ocidl.idl";
import "Shareaza.idl";

[
	uuid(ABC45D7F-EF52-4E5C-986A-93674FE3BBCC),
	version(1.0),
	helpstring("VirusTotal 1.0 Type Library")
]
library VirusTotalLib
{
	importlib("stdole2.tlb");
	
	interface IGeneralPlugin;
	interface ICommandPlugin;

	[
		uuid(76F13243-9F62-4241-AC07-3B359BBE4EC5)
	]
	coclass Plugin
	{
		[default] interface IGeneralPlugin;
		interface ICommandPlugin;
	};
};
