// ImageServices.idl : IDL source for ImageServices
//

// This file will be processed by the MIDL tool to
// produce the type library (ImageServices.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

cpp_quote("#include <ShareazaOM.h>")

[
	uuid(BFB299FD-5773-478B-8033-1977093F1C4C),
	version(1.0),
	helpstring("ImageServices 1.0 Type Library")
]
library ImageServicesLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(5E6309F2-9971-4683-9445-F548E81BEC07),
		helpstring("JPEG Image Service")
	]
	coclass JPEGReader
	{
		[default] interface IUnknown;
	};
	[
		uuid(D427C22F-23FB-4E51-A8B8-70F2036ED3BA),
		helpstring("PNG Image Service")
	]
	coclass PNGReader
	{
		[default] interface IUnknown;
	};
	[
		uuid(DD99484A-33B7-46C2-8387-2FBED7A25A54),
		helpstring("GIF Image Serivice")
	]
	coclass GIFReader
	{
		[default] interface IUnknown;
	};
	[
		uuid(4956C5F5-D9A8-4CBB-8994-F53CF55CFDF5),
		helpstring("AVI Thumbnailing Service")
	]
	coclass AVIThumb
	{
		[default] interface IUnknown;
	};
};


