//
// RazaWebHook.idl : IDL source for RazaWebHook
//
// Copyright (c) Shareaza Development Team, 2008-2010.
// This file is part of SHAREAZA (shareaza.sourceforge.net)
//
// Shareaza is free software; you can redistribute it
// and/or modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2 of
// the License, or (at your option) any later version.
//
// Shareaza is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Shareaza; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
//

import "oaidl.idl";
import "ocidl.idl";
import "objsafe.idl";	// CATID_SafeForScripting, CATID_SafeForInitializing
import "exdisp.idl";	// DWebBrowserEvents2

[
	uuid(6B207D90-4C7A-43C5-863C-AC110209D745),
	version(1.0),
	helpstring("Shareaza Web Download Hook Library")
]
library RazaWebHookLib
{
	importlib("stdole2.tlb");

	[
		object,
		dual,
		oleautomation,
		uuid(974BFF32-401C-45CD-B60D-764E6E34540D),
		nonextensible,
		helpstring("Shareaza Web Download Hook Interface")
	]
	interface IRazaWebHook : IDispatch
	{
		[id(1), helpstring("Send URL to Shareaza.")] HRESULT AddLink([in] VARIANT oLink);
	};

	[
		uuid(0EEDB912-C5FA-486F-8334-57288578C627),
		helpstring("Shareaza Web Download Hook")
	]
	coclass RazaWebHook
	{
		[default] interface IRazaWebHook;
		interface DWebBrowserEvents2;
		interface IObjectWithSite;
	};
};
