// IRC.idl : IDL source for IRC
//

// This file will be processed by the MIDL tool to
// produce the type library (IRC.tlb) and marshalling code.

import "oaidl.idl";
cpp_quote("#include <ShareazaOM.h>")

[
	uuid(6DA0F2C3-850E-411C-876B-972475260115),
	version(1.0),
	helpstring("IRC 1.0 Type Library")
]
library IRCLib
{
	importlib("stdole2.tlb");
	[
		uuid(F12E25F9-F077-45D9-BE7F-368937D7BDDE),
		helpstring("Shareaza IRC Plugin")
	]
	coclass IRCPlugin
	{
		[default] interface IUnknown;
	};
};
